import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Cannabis Seed Laws: Is It Legal to Buy & Grow? | StrainHub Learn", description: "The legal status of cannabis seeds in the US and internationally — seed banks, personal grows, hemp seeds, and the gray areas you need to know." };
export default function Page() {
  return (
    <div className="min-h-screen bg-[#F8F8F0]">
      <div className="border-b border-gray-200 bg-white"><div className="max-w-3xl mx-auto px-6 py-3 flex items-center gap-2 text-xs text-gray-400"><Link href="/" className="hover:text-black">Home</Link><span>/</span><Link href="/learn" className="hover:text-black">Learn</Link><span>/</span><Link href="/learn/seeds" className="hover:text-black">Seeds</Link><span>/</span><span className="text-black font-semibold">Seed Legality</span></div></div>
      <div className="bg-white border-b-2 border-black"><div className="max-w-3xl mx-auto px-6 py-14"><div className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest px-3 py-1.5 rounded-full mb-4" style={{ background: "#f0fdf4", color: "#166534" }}>⚖️ Seeds</div><h1 className="text-4xl md:text-5xl font-black text-black mb-4 leading-tight">Seed Laws & Legality</h1><p className="text-gray-500 text-lg leading-relaxed">Cannabis seeds exist in a unique legal gray area in many jurisdictions. Understanding the specific legal status where you are — not just for cannabis, but specifically for seeds — is essential before purchasing or growing.</p></div></div>
      <div className="max-w-3xl mx-auto px-6 py-12"><div className="grid md:grid-cols-3 gap-10"><div className="md:col-span-2 space-y-10">
        <section><h2 className="text-2xl font-black text-black mb-3">Seeds in the United States</h2><p className="text-gray-600 leading-relaxed text-[17px]">Under federal law, cannabis seeds are Schedule I controlled substances — the same as the plant itself. In recreational states (24 states), adults can legally purchase seeds from licensed dispensaries and grow plants within home cultivation limits (typically 2–6 plants per household). The number of plants allowed, whether clones count separately, and whether outdoor grows are permitted varies by state. In medical-only states, seeds are typically available only to registered medical patients from licensed dispensaries. In prohibited states, seeds are fully illegal. Notably, the Farm Bill (2018) legalized hemp seeds — seeds from plants with under 0.3% THC — which are now openly sold online and in stores nationally.</p></section>
        <section><h2 className="text-2xl font-black text-black mb-3">Online Seed Banks: The Gray Area</h2><p className="text-gray-600 leading-relaxed text-[17px]">Hundreds of online seed banks — primarily based in the Netherlands, UK, Spain, and Canada — ship cannabis seeds internationally, including to the US. They typically market seeds as &quot;souvenirs&quot; or &quot;collectibles&quot; sold &quot;for genetic preservation purposes only, not for cultivation.&quot; This disclaimer has limited legal meaning but reduces the appearance of intentional distribution. US Customs seizes packages containing cannabis seeds regularly — most reputable seed banks offer re-ship guarantees. The practical prosecution risk for an individual receiving a small personal seed order is extremely low (no recorded US federal prosecutions for seed imports for personal use), but the legal risk is real. Purchasing from licensed dispensaries in legal states is the only legally unambiguous option in the US.</p></section>
        <section><h2 className="text-2xl font-black text-black mb-3">International Seed Laws</h2><p className="text-gray-600 leading-relaxed text-[17px]">Seed legality varies dramatically internationally. <strong>Netherlands:</strong> Seeds are legal to sell and possess — the Amsterdam seed industry was built on this (Sensi Seeds, Dutch Passion, Serious Seeds all operate there). <strong>Spain:</strong> Personal cultivation for private use is decriminalized; seeds are sold openly in &quot;grow shops.&quot; <strong>UK:</strong> Seeds are in a legal gray area — possession is technically illegal under the Misuse of Drugs Act, but seeds are sold openly as &quot;collectibles&quot; with minimal enforcement. <strong>Canada:</strong> Seeds fully legal — sold in licensed stores and online from provincial retailers. <strong>Germany:</strong> As of 2024, adults can grow up to 3 plants; seeds for personal cultivation are legal. <strong>Australia:</strong> Seeds are illegal nationally but enforcement is inconsistent.</p></section>
        <section><h2 className="text-2xl font-black text-black mb-3">Hemp Seeds: Fully Legal</h2><p className="text-gray-600 leading-relaxed text-[17px]">Hemp seeds — from cannabis plants bred to contain under 0.3% THC (dry weight) — were fully federalized under the Agriculture Improvement Act (Farm Bill) of 2018. Hemp seeds for cultivation are legal to buy, sell, and grow in all 50 states, though state agricultural departments may require specific licenses for commercial hemp cultivation. Hemp seeds for food (hulled hemp seeds, hemp seed oil, hemp seed protein powder) are legal to sell as food under FDA oversight. This created a significant market — hemp seeds are widely sold in grocery stores, on Amazon, and through mainstream retailers. Note: germinating commercial hemp seeds for grain/fiber production is different from growing high-cannabinoid hemp flower, which faces additional regulatory scrutiny.</p></section>
      </div>
      <div className="space-y-4 md:sticky md:top-6 self-start">
        <div className="bg-black rounded-2xl p-6 text-white">
          <div className="text-[10px] font-black uppercase tracking-widest text-lime-400 mb-4">⚖️ Legal Snapshot</div>
          <div className="space-y-2">
            {[{flag:"🇺🇸",place:"24 US states",note:"Legal at dispensaries"},{flag:"🌿",place:"Hemp seeds",note:"Legal all 50 states (2018)"},{flag:"🇳🇱",place:"Netherlands",note:"Fully legal to sell"},{flag:"🇨🇦",place:"Canada",note:"Fully legal nationwide"},{flag:"⚠️",place:"US federal",note:"Schedule I — still illegal"}].map(({flag,place,note})=>(<div key={place} className="flex items-start gap-3 py-2 border-b border-white/10 last:border-0"><span className="text-lg">{flag}</span><div><div className="text-white font-bold text-xs">{place}</div><div className="text-gray-400 text-[11px]">{note}</div></div></div>))}
          </div>
        </div>
        <div className="bg-red-50 border-2 border-red-200 rounded-2xl p-4">
          <p className="text-red-700 text-xs font-bold">⚠️ Never travel internationally with seeds — even between legal countries.</p>
        </div>
        <Link href="/learn/seeds" className="flex items-center gap-2 px-4 py-3 rounded-xl border-2 border-black bg-white hover:bg-black hover:text-white transition-all text-sm font-bold text-black group"><span className="group-hover:-translate-x-1 transition-transform">←</span> Back to Seeds</Link>
      </div>
      </div></div></div>
  );
}